#ifndef CONSTANTS
#define CONSTANTS

#include <stdbool.h>

extern const char *MW_CLIENT_NAME;
extern const bool MW_CLEAN_SESSION;

#define EXPORT_READONLY 1
#define EXPORT_WRITABLE 2
#define EXPORT_SUBSCRIBE 4
#define EXPORT_METHOD 8

#define EXPORT_MONITOR EXPORT_READONLY
#define EXPORT_PARAMETER (EXPORT_WRITABLE | EXPORT_SUBSCRIBE)
#define EXPORT_ACTION (EXPORT_WRITABLE | EXPORT_METHOD)
#define EXPORT_CONTROL EXPORT_WRITABLE

enum MqttConnectionState {
  STATUS_CONNECTING,
  STATUS_CONNACK_RECVD,
  STATUS_CONNECTED,
  STATUS_DISCONNECTING,
  STATUS_DISCONNECTED,
  STATUS_INTERNAL_ERROR,
  STATUS_DOWN
};

#define UNUSED(x) (void)(x)

#endif /* CONSTANTS */
