//
// Generated by sedonac 1.2.28
// 22-Mai-2021 17:56
//

#ifndef SEDONAC_SEDONA_PLATFORM_H
#define SEDONAC_SEDONA_PLATFORM_H

#ifndef PLATFORM_ID
#define PLATFORM_ID "tridium-generic-unix-1.2.28"
#endif

#endif
